README.md
Fixes #
Reference to #
```release-note
NONE
```
=> Fix broken links and correct spelling of ElasticDL

.gitignore
=> Add IDE-related settings to .gitignore

.isort.cfg, .pre-commit-config.yaml, .travis.yml, Dockerfile, ftlib/__init__.py, ftlib/consensus/basic.py, ftlib/consensus/consensus_status.py, ftlib/consensus/shared_storage/__init__.py, ftlib/consensus/shared_storage/master_server.py, ftlib/consensus/shared_storage/utils.py, ftlib/framework/basic.py, ftlib/framework/dummy_nccl/__init__.py, ftlib/framework/framework_status.py, ftlib/framework/pytorch/__init__.py, ftlib/ftlib_status.py, test/generic_test.py, test/pytorch_test.py
**We should merge this first before new PRs** so we can follow the same styles and best practices Using pre-commit to enforce this. Run `pre-commit run --files $(find ftlib test -name '*.py' -print0 | tr '\0' ' ')` to automatically fix all the issues detected by pre-commit hooks.
Fixes #
Reference to #
```release-note
NONE
```
=> Setup pre-commit check and fix all existing issues

README.md
Fixes #
Reference to #
```release-note
NONE
```
=> Add Travis and LICENSE badges

.travis.yml, Dockerfile, deploy/Dockerfile, deploy/FindNCCL.cmake, deploy/ftlib-rbac.yaml, deploy/ftlib-test.yaml, requirements.txt
Part of #17. This PR adds necessary Dockerfile, k8s configurations. Note that the result of ` kubectl apply -f deploy/ftlib-test.yaml` won't be verified here yet. We'll add follow up PR to check the deployment status.
Fixes #
Reference to #
```release-note
NONE
```
=> Add docker image and k8s configurations for testing on Travis

README.md, ROADMAP.md
1. add short-term plan to ROADMAP file 
2. update readme.md
Fixes #
Reference to #
/cc @terrytangyuan @pendoragon  @ddysher 
```release-note
NONE
```
=> feat: add roadmap and update readme

ftlib/__init__.py, ftlib/framework/pytorch/__init__.py
Fixes #
Reference to #
```release-note
NONE
```
=> Fix typo: pytroch -> pytorch

.isort.cfg, .travis.yml, README.md, deploy/Dockerfile, deploy/ftlib-test.yaml, ftlib/ftlib_status.py, requirements-dev.txt, setup.py
Fixes #18. Fixed a few typos in README. Also fixed the following exception:
```
---> 13 class FTRebuildStatus(ConsensusStatus):
14     ABORT = 2
/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/enum.py in __prepare__(metacls, cls, bases)
117         enum_dict = _EnumDict()
118         # inherit previous flags and _generate_next_value_ function
--> 119         member_type, first_enum = metacls._get_mixins_(bases)
120         if first_enum is not None:
121             enum_dict['_generate_next_value_'] = getattr(first_enum, '_generate_next_value_', None)
/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/enum.py in …
```
=> Set up Python package structure and a couple fixes

ftlib/__init__.py
Fix issue with `Local variable might be referenced before assignment` for both `master_addr` and `succeeded`. Also check whether `master_addr` has been returned as part of `consensus.get_rank_size()`.
Fixes #
Reference to #
/cc @zw0610 @gaocegege @ddysher @pendoragon
```release-note
NONE
```
=> Initialize master address and check None for rebuild()

.gitignore
To prevent accidentally pushing the generated proto files.
Fixes #
Reference to #
/cc @zw0610 @gaocegege @ddysher @pendoragon
```release-note
NONE
```
=> Include proto files in .gitignore

ftlib/framework/dummy_nccl/__init__.py, ftlib/framework/dummy_nccl/src/fault_tolerant_lib.cxx
Add broadcast op using NCCL communication library. Also renamed `checkAllreduce` to `checkOpResult` so that it can be reused for both ops. Note that https://github.com/caicloud/ftlib/pull/33 only renames certain related files so there won't be a lot of conflicts.
Fixes https://github.com/caicloud/ftlib/issues/5
Reference to #
/cc @zw0610 @gaocegege @ddysher @pendoragon
```release-note
NONE
```
=> Add NCCL broadcast op

ftlib/commlib/pytorch/impl.py, ftlib/impl.py, ftlib/rank_assign_scheme.py
fix two issues:
1. with different python session (different worker), default hash function for string differs, resulting in different master node address
2. with new member join, the communication library rebuild procedure requires aborting communicator step first
Fixes #
Reference to #
/cc @terrytangyuan
```release-note
NONE
```
=> fix: address issues on further tests

.isort.cfg, ftlib/impl.py, test/data.py, test/pytorch-gossip-tricky-data.py
Add an example on how we can handle data given the change of rank and size of the worker in a distributed training job.
The basic idea in this demo is to replace the built-in `iter` with a customized iterator, censoring changes in `FTLib` every time `__next__` is called.  
Fixes #
Reference to #
/cc @terrytangyuan @gaocegege @pendoragon @ddysher 
```release-note
NONE
```
=> feat: add data io demo

ftlib/consensus/gossip/impl.py
Fixes #
Reference to #
/cc @zw0610 @gaocegege 
```release-note
NONE
```
=> Fix typo: sefl -> self

docs/design/ftlib.md, ftlib/commlib/nccl/impl.py, ftlib/impl.py, test/deprecated-tests/generic_test.py
* `dummy_NCCL` should've been renamed to `NCCL`.
* `self._wait_time` is missing in `NCCL` implementation.
* `wait_weights_ready` should've been renamed to `wait_gradients_ready`. Otherwise all tests will fail.
Fixes #
Reference to #
/cc @zw0610 @gaocegege 
```release-note
NONE
```
=> Fix a couple of issues in implementations

ftlib/commlib/pytorch/impl.py, ftlib/consensus/gossip/impl.py, ftlib/consensus/gossip/test.py, ftlib/impl.py, test/kubernetes/Dockerfile, test/kubernetes/ftlib-deployment.yaml, test/kubernetes/script/main.py, test/kubernetes/script/test.py
Fixes #
Reference to #
```release-note
NONE
```
=> feat: add kubernetes example

ftlib/impl.py, ftlib/rank_assign_scheme.py
In FTLit, there are some issues with `execute` and `_wrap_api`. This PR fixes issues on logging, error handling and timing.
Fixes #
Reference to #
```release-note
NONE
```
=> fix issue on logging, error handling and timing

ftlib/commlib/pytorch/impl.py, ftlib/consensus/gossip/impl.py, ftlib/impl.py
During the test, we found that, it is rather unstable of ftlib that it will retry rebuild process for multiple times when worker lost or join.
It is because the `_rebuild` will rush to rebuilding communicator once `consensus.confirm` returns success. We need to introduce a buffer mechanism that prevent wasting time in communicator rebuilding.
Fixes #
Reference to #
/cc @pendoragon @terrytangyuan 
```release-note
NONE
```
=> feat: increase stability of ftlib.rebuild

ftlib/commlib/pytorch/impl.py, ftlib/consensus/gossip/impl.py, ftlib/impl.py, test/kubernetes/Dockerfile, test/kubernetes/script/main.py
Before update, there are 2 issues:
1. cannot decrease to 1 -> test main.py need to determine whether skip allreduce or re-wrap model with ddp
2. cannot increase (re-init pytorch process group times out) -> upgrade to pytorch 1.3.0 fixes this issue
Fixes #
Reference to #
/cc @terrytangyuan @pendoragon 
```release-note
NONE
```
=> Udpate example

ftlib/utils/kubernetes/__init__.py, ftlib/utils/kubernetes/svc.py, test/kubernetes/script/main.py
The previous example will overload loss easily. We replace it with a polynomial learning example.
P.S. the loss under the polynomial learning example does not decrease monotonically. But it does not become inf/nan after several steps.
Fixes #
Reference to #
/cc @terrytangyuan @ddysher 
```release-note
NONE
```
=> feat: replace dummy date+lenet with a polynomial example

test/kubernetes/ftlib-deployment.yaml
Add environment PYTHONUNBUFFERED=0
Fixes #
Reference to #
```release-note
NONE
```
=> fix: python print not showing in docker

ftlib/impl.py, ftlib/rank_assign_scheme.py
Address rank-assign issue
Fixes #51 
Reference to #
```release-note
NONE
```
=> fix: address rank-assign issue

test/pytorch-gossip/pytorch-gossip_test.py
Fixes #
Reference to #
```release-note
NONE
```
=> fix: update demo script after ftlib code changes

ftlib/commlib/pytorch/impl.py
Temporarily expose pytorch api for numpy ndarray.
Fixes #
Reference to #
```release-note
NONE
```
=> feat: wrap torch api for numpy ndarray

ftlib/commlib/pytorch/impl.py
merge to the master branch
Fixes #
Reference to #
/cc @gaocegege 
```release-note
NONE
```
=> feat: wrap torch api for numpy ndarray (#58)

deploy/Dockerfile
Fixes #
Reference to #
/cc @zw0610 
```release-note
NONE
```
=> Fix CI: remove already deleted build_with_pybind11.sh

ftlib/commlib/gloo/CMakeLists.txt, ftlib/commlib/gloo/Dockerfile, ftlib/commlib/gloo/__init__.py, ftlib/commlib/gloo/impl.py, ftlib/commlib/gloo/src/gloo_lib.cxx, ftlib/commlib/nccl/impl.py
Add Gloo support
Fixes #
Reference to #
```release-note
NONE
```
=> feat: add gloo support with numpy

ftlib/commlib/gloo/impl.py
This fixes the pre-commit check on master branch.
Fixes #
Reference to #
/cc @zw0610 
```release-note
NONE
```
=> Fix pre-commit check in Gloo implementation

ftlib/consensus/gossip/impl.py, ftlib/consensus/gossip/memberlist/main.go
we add further option of tcp_timeout for initializing Gossip.
Fixes #
Reference to #
```release-note
NONE
```
=> feat: add option for tcp_timeout

ftlib/consensus/gossip/impl.py, ftlib/consensus/gossip/memberlist/main.go, ftlib/impl.py
Fixing mismatch between time.Duration and C.Int
Fixes #
Reference to #
```release-note
NONE
```
=> Custom config memberlist

OWNERS
Add @skydoorkai and @QiJune as reviewers.
Fixes #
Reference to #
/cc @pendoragon 
```release-note
NONE
```
=> feat: update OWNER file

ftlib/commlib/pytorch/impl.py
enable grad_sync_done for a list of np.ndarrays
Fixes #
Reference to #
```release-note
NONE
```
=> feat: update grad_sync_done

test/deprecated-tests/generic_test.py
Fixes #
Reference to #
/cc @pendoragon @zw0610 @gaocegege 
```release-note
NONE
```
=> Fix CI build

.isort.cfg, test/deprecated-tests/pytorch_test.py, test/deprecated-tests/tricky-data/pytorch-gossip-tricky-data.py
After the travis ci is re-configured, this pr address issues occur after `FTAllReduceStatus` is renamed to `FTCollectiveStatus`
Fixes #
Reference to #
```release-note
NONE
```
=> feat: fix travis ci after rename FTAllReduceStatus
